/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyNavbarComponent {
    }
}
export interface MyNavbarComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyNavbarComponentElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyNavbarComponentElementEventMap {
        "toggleMenu": boolean;
        "menuclicked": string;
    }
    interface HTMLMyNavbarComponentElement extends Components.MyNavbarComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyNavbarComponentElementEventMap>(type: K, listener: (this: HTMLMyNavbarComponentElement, ev: MyNavbarComponentCustomEvent<HTMLMyNavbarComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyNavbarComponentElementEventMap>(type: K, listener: (this: HTMLMyNavbarComponentElement, ev: MyNavbarComponentCustomEvent<HTMLMyNavbarComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyNavbarComponentElement: {
        prototype: HTMLMyNavbarComponentElement;
        new (): HTMLMyNavbarComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-navbar-component": HTMLMyNavbarComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyNavbarComponent {
        "onMenuclicked"?: (event: MyNavbarComponentCustomEvent<string>) => void;
        "onToggleMenu"?: (event: MyNavbarComponentCustomEvent<boolean>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-navbar-component": MyNavbarComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-navbar-component": LocalJSX.MyNavbarComponent & JSXBase.HTMLAttributes<HTMLMyNavbarComponentElement>;
        }
    }
}
